# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build
ENV HELLO_TAG="Helloooo World!"

# Set destination for COPY

WORKDIR /app

# Download Go modules

# Copy the source code.

COPY *.go ./

# Build
RUN go build -o /greeter greeter.go

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /greeter /greeter

EXPOSE 80

#USER nonroot:nonroot

ENV HELLO_TAG="Helloooo World!"

ENTRYPOINT ["/greeter"]
